### ISSUE TITLE
quickfill: Crash when pasting copied area into paint.net

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#254]
Not exactly sure what causes it. It happened when I selected a small area (about 3x10 px) using a circular selection and tried to copy paste it from PixiEditor into paint.net. paint.net also displayed a similar error. Here is the crash log (the crash message says "error while calling openclipboard"):
```
-------Crash message-------
System.Runtime.InteropServices.COMException: Ошибка при вызове OpenClipboard (0x800401D0 (CLIPBRD_E_CANT_OPEN))

-------Stack trace-------
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataObject(Object data, Boolean copy)
   at PixiEditor.Models.Controllers.ClipboardController.CopyToClipboard(Layer[] layers, Coordinates[] selection, Int32 originalImageWidth, Int32 originalImageHeight, SerializableDocument document) in C:\Users\egor0\source\repos\PixiEditor\PixiEditor\Models\Controllers\ClipboardController.cs:line 67
   at PixiEditor.Models.Controllers.ClipboardController.CopyToClipboard(Document document) in C:\Users\egor0\source\repos\PixiEditor\PixiEditor\Models\Controllers\ClipboardController.cs:line 79
   at PixiEditor.ViewModels.SubViewModels.Main.ClipboardViewModel.Copy(Object parameter) in C:\Users\egor0\source\repos\PixiEditor\PixiEditor\ViewModels\SubViewModels\Main\ClipboardViewModel.cs:line 58
   at PixiEditor.ViewModels.SubViewModels.Main.ClipboardViewModel.Cut(Object parameter) in C:\Users\egor0\source\repos\PixiEditor\PixiEditor\ViewModels\SubViewModels\Main\ClipboardViewModel.cs:line 40
   at PixiEditor.Helpers.RelayCommand.Execute(Object parameter) in C:\Users\egor0\source\repos\PixiEditor\PixiEditor\Helpers\RelayCommand.cs:line 40
   at PixiEditor.Models.Controllers.Shortcuts.Shortcut.Execute() in C:\Users\egor0\source\repos\PixiEditor\PixiEditor\Models\Controllers\Shortcuts\Shortcut.cs:line 42
   at PixiEditor.Models.Controllers.Shortcuts.ShortcutController.KeyPressed(Key key, ModifierKeys modifiers) in C:\Users\egor0\source\repos\PixiEditor\PixiEditor\Models\Controllers\Shortcuts\ShortcutController.cs:line 36
   at PixiEditor.ViewModels.SubViewModels.Main.IoViewModel.KeyDown(Object parameter) in C:\Users\egor0\source\repos\PixiEditor\PixiEditor\ViewModels\SubViewModels\Main\IoViewModel.cs:line 55
   at PixiEditor.Helpers.RelayCommand.Execute(Object parameter) in C:\Users\egor0\source\repos\PixiEditor\PixiEditor\Helpers\RelayCommand.cs:line 40
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at PixiEditor.App.Main()
```

**Comment by Equbuxu** [comment]
related: https://stackoverflow.com/questions/68666/clipbrd-e-cant-open-error-when-setting-the-clipboard-from-net

**Comment by flabbet** [comment]
Jesus, I am not scared how badly clipboard is implemented

**Comment by CPKreuz** [comment]
what the heck
