### ISSUE TITLE
ViewModelMain.Current is null when the recovered documents are being loaded

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#405]
```csharp
public void RecoverDocuments()
{
    MainWindow window = MainWindow.CreateWithDocuments(CrashReport.RecoverDocuments());
    
    Application.Current.MainWindow = window;
    window.Show();
    hasRecoveredDocuments = false;
}
```
This is the function that recovers the documents from a crash report. CrashReport.RecoverDocuments() creates Document objects. This happens before the main window and viewmodelmain are created. Document, however, expects the ViewModelMain to exist during construction and afterwards. This causes crashes in various places, like

```
   at PixiEditor.Models.DataHolders.Document.SetAsActiveOnClick(Object obj) in D:\a\1\s\PixiEditor\Models\DataHolders\Document\Document.cs:line 212
   at PixiEditor.Helpers.RelayCommand.Execute(Object parameter) in D:\a\1\s\PixiEditor\Helpers\RelayCommand.cs:line 40
   ...
```

```
   at PixiEditor.Models.DataHolders.Document.UpdateRecentlyOpened(String newPath) in D:\a\1\s\PixiEditor\Models\DataHolders\Document\Document.IO.cs:line 57
   at PixiEditor.Models.DataHolders.Document.set_DocumentFilePath(String value) in D:\a\1\s\PixiEditor\Models\DataHolders\Document\Document.IO.cs:line 20
   at PixiEditor.Models.DataHolders.Document.SaveWithDialog() in D:\a\1\s\PixiEditor\Models\DataHolders\Document\Document.IO.cs:line 40
   at PixiEditor.ViewModels.SubViewModels.Main.FileViewModel.SaveDocument(Object parameter) in D:\a\1\s\PixiEditor\ViewModels\SubViewModels\Main\FileViewModel.cs:line 252
   ...
```
etc.

Sometimes documents try to access the ViewModelMain right away, throwing exceptions that get caught in CrashReport.RecoverDocument(). Those documents are then discarded, even though there is nothing wrong with them

**Comment by Equbuxu** [comment]
#393 is the same bug
