### ISSUE TITLE
Crash with merge node

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#682]
-------Crash message-------
System.NullReferenceException: Object reference not set to an instance of an object.

-------Stack trace-------
   at PixiEditor.ChangeableDocument.Changeables.Graph.Nodes.MergeNode.Merge(DrawingSurface target, RenderContext context)
   at PixiEditor.ChangeableDocument.Changeables.Graph.Nodes.MergeNode.OnPaint(RenderContext context, DrawingSurface target)
   at PixiEditor.ChangeableDocument.Changeables.Graph.RenderOutputProperty.<ChainToPainterValue>b__9_0(RenderContext ctx, DrawingSurface surface)
   at PixiEditor.ChangeableDocument.Changeables.Graph.Nodes.MergeNode.Merge(DrawingSurface target, RenderContext context)
   at PixiEditor.ChangeableDocument.Changeables.Graph.Nodes.MergeNode.OnPaint(RenderContext context, DrawingSurface target)
   at PixiEditor.ChangeableDocument.Changeables.Graph.RenderOutputProperty.<ChainToPainterValue>b__9_0(RenderContext ctx, DrawingSurface surface)
   at PixiEditor.ChangeableDocument.Changeables.Graph.Nodes.OutputNode.OnExecute(RenderContext context)
   at PixiEditor.ChangeableDocument.Changeables.Graph.NodeGraph.Execute(RenderContext context)
   at PixiEditor.ChangeableDocument.Rendering.DocumentRenderer.RenderPreview(DrawingSurface renderOn, ChunkResolution resolution, Int32 frame, String elementToRenderName)
   at PixiEditor.Views.Visuals.PreviewPainterControl.Draw(DrawingSurface surface)
   at Drawie.Interop.Avalonia.Core.Controls.DrawieControl.<RenderFrame>b__6_0()
   at Drawie.Interop.Avalonia.Vulkan.Vk.VulkanResources.Render(PixelSize size, Action renderAction)
   at Drawie.Interop.Avalonia.Core.Controls.InteropControl.UpdateFrame()
   at Avalonia.Rendering.Composition.Compositor.CommitCore()
   at Avalonia.Rendering.Composition.Compositor.Commit()
   at Avalonia.Media.MediaContext.CommitCompositorsWithT

**Comment by flabbet** [comment]
Possibly fixed in 2.0.0.29
