### ISSUE TITLE
Crash when opening the export menu for canvases of width or height 1

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#691]
Make a new 1x256 or a 256x1 image, press File -> Export

```
PixiEditor 2.0.0.30 Beta Steam Build x64 crashed on 2024.12.09 at 23:48:25 +03:00
Application started 2024.12.09 23:11:09, 0 00:00.15 ago
Report: 18a9aac2-ea96-4234-a75b-bfb8a0a278bf

-----System Information----
General:
  OS: Microsoft Windows NT 10.0.22000.0

CPU:
  Name: AMD Ryzen 7 2700 Eight-Core Processor          
  Speed: 3.37 GHz
  Max Speed: 3.20 GHz

GPU:
  Name: NVIDIA RTX A4000
  Driver: 31.0.15.2727

Memory:
  Available: 3.92  GB
  Total: 17.13  GB

--------Command Log--------

PixiEditor.File.Export | CanExecute: True | -0.106s ago | 2024-12-09T23:48:25.3252340+03:00

-----------State-----------
Environment:
  Thread Count: 63
Analytics:
  Analytics Id: 2c4ce6a7-975e-47f9-bf9f-689a2a3bc868

Culture:
  Selected language: "en"
  Current Culture: ja-JP
  Current UI Culture: ja-JP

Preferences:
  Has shared toolbar enabled: False
  Right click mode: SecondaryColor
  Has Rich presence enabled: True
  Debug Mode enabled: True

UI:
  MainWindow not null: True
  MainWindow Size: 0, 0, 1936, 1048
  MainWindow State: Maximized

ViewModels:
  Has active updateable change: False
  Current Tool: "MoveViewport"
  Primary Color: #ff000000
  Secondary Color: #ffffffff

Active Document: 
  Size: (1; 256)
  Layer Count: 1
  Has all changes saved: True
  Horizontal Symmetry Enabled: False
  Horizontal Symmetry Value: 128
  Vertical Symmetry Enabled: False
  Vertical Symmetry Value: 0.5
  Updateable Change Active: False
  Transform: Not active

-------Crash message-------
System.ArgumentException: Width and height must be >=1


-------Stack trace-------
   at Drawie.Backend.Core.Surface..ctor(ImageInfo info)
   at Drawie.Backend.Core.Surface..ctor(VecI size)
   at Drawie.Backend.Core.Surface.ResizeNearestNeighbor(VecI newSize)
   at PixiEditor.Views.Dialogs.ExportFilePopup.<>c__DisplayClass64_0.<RenderImagePreview>b__1()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at PixiEditor.Desktop.Program.Main(String[] args)
   ```

**Comment by flabbet** [comment]
#695
